require('expose?$!expose?jQuery!jquery');
require('spservices/dist/jquery.SPServices.js');
require('lodash');
var React = require('react');
require('flexslider');
require('flexslider/flexslider.css');
require('selectize');
require('selectize/dist/css/selectize.bootstrap3.css');
require('./main.css');
require('./slider-component.js');
